export const products = [
  {
    id: 1,
    name: "Remera Blanca",
    url: "https://tienda.guantexindustrial.com.ar/713-large_default/remera-algodon-jersey-blanco-talle-m.jpg",
    price: 1500,
    categoria: "remeras",
    stock: 100,
    initial: 1,
    description:
      "Remera confeccionada en algodón y jersey con cuello a la base.",
  },
  {
    id: 2,
    name: "Remera Azul",
    url: "https://tienda.guantexindustrial.com.ar/700-large_default/remera-algodon-jersey-azul-talle-xxxl.jpg",
    price: 2450,
    categoria: "remeras",
    stock: 100,
    initial: 1,
    description:
      "Remera confeccionada en algodón y jersey con cuello a la base.",
  },
  {
    id: 3,
    name: "Chomba Lisa",
    url: "https://tienda.guantexindustrial.com.ar/725-large_default/chomba-pique-azul-talle-xl.jpg",
    price: 890,
    categoria: "chombas",
    stock: 100,
    initial: 1,
    description: "Chomba lisa color naranja",
  },
  {
    id: 4,
    name: "Chomba Azul",
    url: "https://tienda.guantexindustrial.com.ar/725-large_default/chomba-pique-azul-talle-xl.jpg",
    price: 890,
    categoria: "chombas",
    stock: 100,
    initial: 1,
    description: "Chomba confeccionada en tela piqué con cuello polo.",
  },
  {
    id: 5,
    name: "Pantalon Gris",
    url: "https://tienda.guantexindustrial.com.ar/1202-large_default/pantalon-gaucho-azulino-talle-60.jpg",
    price: 334,
    categoria: "pantalones",
    stock: 100,
    initial: 1,
    description: "Product description 4",
  },
  {
    id: 6,
    name: "Pantalon Marron",
    url: "https://tienda.guantexindustrial.com.ar/1601-large_default/pantalon-gaucho-beige-talle-40.jpg",
    price: 989,
    categoria: "pantalones",
    stock: 100,
    initial: 1,
    description:
      "Costuras reforzadas con atraques. Algodón 100%. Hilos 100% poliéster.",
  },
  {
    id: 7,
    name: "Pantalon Negro",
    url: "https://tienda.guantexindustrial.com.ar/2155-large_default/pantalon-gaucho-cargo-negro-talle-60.jpg",
    price: 8212,
    categoria: "pantalones",
    stock: 100,
    initial: 1,
    description:
      "Costuras reforzadas con atraques. Algodón 100%. Hilos 100% poliéster. Bolsillos a los costados con fuelle. Cierres dieléctrico. ",
  },
];
